//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Repop_Companion.DataModels
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class RepopdataEntities : DbContext
    {
        public RepopdataEntities()
            : base("name=RepopdataEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<C_dbINFO> C_dbINFO { get; set; }
        public virtual DbSet<Ability> Abilities { get; set; }
        public virtual DbSet<Crafting_Components> Crafting_Components { get; set; }
        public virtual DbSet<Crafting_Filters> Crafting_Filters { get; set; }
        public virtual DbSet<Fitting> Fittings { get; set; }
        public virtual DbSet<Hacking> Hackings { get; set; }
        public virtual DbSet<Harvestable_Regions> Harvestable_Regions { get; set; }
        public virtual DbSet<Item_Armor> Item_Armor { get; set; }
        public virtual DbSet<Item_Armor_Energy> Item_Armor_Energy { get; set; }
        public virtual DbSet<Item_Stackable> Item_Stackable { get; set; }
        public virtual DbSet<Item_Value> Item_Value { get; set; }
        public virtual DbSet<Item_Weapons> Item_Weapons { get; set; }
        public virtual DbSet<Item> Items { get; set; }
        public virtual DbSet<Path> Paths { get; set; }
        public virtual DbSet<Prop> Props { get; set; }
        public virtual DbSet<Recipe> Recipes { get; set; }
        public virtual DbSet<ResourceAttribute> ResourceAttributes { get; set; }
        public virtual DbSet<Share> Shares { get; set; }
        public virtual DbSet<Shop> Shops { get; set; }
        public virtual DbSet<Skill> Skills { get; set; }
        public virtual DbSet<Species> Species { get; set; }
        public virtual DbSet<Structure> Structures { get; set; }
        public virtual DbSet<Tip> Tips { get; set; }
        public virtual DbSet<Abilities_ActivationData> Abilities_ActivationData { get; set; }
        public virtual DbSet<Abilities_WeaponData> Abilities_WeaponData { get; set; }
        public virtual DbSet<Item_Crafting_Components> Item_Crafting_Components { get; set; }
        public virtual DbSet<Item_Crafting_Filters> Item_Crafting_Filters { get; set; }
        public virtual DbSet<Item_Power_Source> Item_Power_Source { get; set; }
        public virtual DbSet<Item_Stores_Power> Item_Stores_Power { get; set; }
        public virtual DbSet<Recipe_Agents> Recipe_Agents { get; set; }
        public virtual DbSet<Recipe_Books> Recipe_Books { get; set; }
        public virtual DbSet<Recipe_Ingredients> Recipe_Ingredients { get; set; }
        public virtual DbSet<Recipe_Results> Recipe_Results { get; set; }
        public virtual DbSet<Recipe_Skill_Range> Recipe_Skill_Range { get; set; }
        public virtual DbSet<Shop_Inventory_List> Shop_Inventory_List { get; set; }
        public virtual DbSet<Shop_To_Inventory_List> Shop_To_Inventory_List { get; set; }
        public virtual DbSet<Species_Results> Species_Results { get; set; }
    }
}
