//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Repop_Companion.DataModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class Abilities_ActivationData
    {
        public long abilityID { get; set; }
        public string activationType { get; set; }
        public Nullable<double> radius { get; set; }
        public string range { get; set; }
    }
}
namespace Repop_Companion.DataModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class Abilities_WeaponData
    {
        public long abilityID { get; set; }
        public Nullable<double> weaponAccuracyMod { get; set; }
        public Nullable<double> weaponDamageMod { get; set; }
        public Nullable<double> weaponEnduranceMod { get; set; }
        public Nullable<double> weaponEnergyMod { get; set; }
        public Nullable<double> weaponGlobalCooldownMod { get; set; }
        public Nullable<double> weaponMomentumMod { get; set; }
        public Nullable<double> weaponRangeMod { get; set; }
        public Nullable<double> weaponSpeedMod { get; set; }
    }
}
namespace Repop_Companion.DataModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ability
    {
        public long abilityID { get; set; }
        public string displayName { get; set; }
        public string displayDescription { get; set; }
        public Nullable<long> iconID { get; set; }
        public Nullable<long> skillID { get; set; }
        public Nullable<long> skillMin { get; set; }
        public string recharge { get; set; }
        public string globalCoolDown { get; set; }
        public string visualizationTimer { get; set; }
        public Nullable<long> enduranceCost { get; set; }
        public Nullable<long> energyCost { get; set; }
        public Nullable<long> momentumCost { get; set; }
        public string abilType { get; set; }
    }
}
namespace Repop_Companion.DataModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_dbINFO
    {
        public long version { get; set; }
        public string date { get; set; }
        public string time { get; set; }
        public string updatedBy { get; set; }
    }
}
namespace Repop_Companion.DataModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class Crafting_Components
    {
        public long componentID { get; set; }
        public string displayName { get; set; }
        public string displayDescription { get; set; }
        public long iconID { get; set; }
    }
}
namespace Repop_Companion.DataModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class Crafting_Filters
    {
        public long filterID { get; set; }
        public string displayName { get; set; }
        public string displayDescription { get; set; }
    }
}
namespace Repop_Companion.DataModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class Fitting
    {
        public long fittingID { get; set; }
        public string displayName { get; set; }
        public string displayDescription { get; set; }
    }
}
namespace Repop_Companion.DataModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class Hacking
    {
        public long hackingID { get; set; }
        public string title { get; set; }
        public string recipe { get; set; }
        public Nullable<long> skill { get; set; }
    }
}
namespace Repop_Companion.DataModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class Harvestable_Regions
    {
        public long harvestableRegionID { get; set; }
        public string areaID { get; set; }
        public Nullable<long> levelMin { get; set; }
        public Nullable<long> levelMax { get; set; }
        public Nullable<long> minCount { get; set; }
        public Nullable<long> maxCount { get; set; }
        public Nullable<long> propID { get; set; }
        public Nullable<long> replenishRate { get; set; }
        public Nullable<long> isSeasonal { get; set; }
    }
}
namespace Repop_Companion.DataModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class Item
    {
        public long itemID { get; set; }
        public string displayName { get; set; }
        public string displayDescription { get; set; }
        public long iconID { get; set; }
    }
}
namespace Repop_Companion.DataModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class Item_Armor
    {
        public long itemID { get; set; }
        public string armorType { get; set; }
        public Nullable<long> armorReduction { get; set; }
        public string equipLOCation { get; set; }
    }
}
namespace Repop_Companion.DataModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class Item_Armor_Energy
    {
        public long itemID { get; set; }
        public Nullable<long> maxEnergy { get; set; }
        public Nullable<long> poolSplit { get; set; }
        public Nullable<long> rechargeRate { get; set; }
        public Nullable<double> rechargeDelay { get; set; }
    }
}
namespace Repop_Companion.DataModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class Item_Crafting_Components
    {
        public long itemID { get; set; }
        public long componentID { get; set; }
    }
}
namespace Repop_Companion.DataModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class Item_Crafting_Filters
    {
        public long itemID { get; set; }
        public long filterID { get; set; }
    }
}
namespace Repop_Companion.DataModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class Item_Power_Source
    {
        public long itemID { get; set; }
        public long powerIndex { get; set; }
    }
}
namespace Repop_Companion.DataModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class Item_Stackable
    {
        public long itemID { get; set; }
        public Nullable<long> defaultStackSize { get; set; }
        public Nullable<long> maxStackSize { get; set; }
    }
}
namespace Repop_Companion.DataModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class Item_Stores_Power
    {
        public long itemID { get; set; }
        public long maxStorage { get; set; }
    }
}
namespace Repop_Companion.DataModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class Item_Value
    {
        public long itemID { get; set; }
        public Nullable<long> value { get; set; }
        public string currencyType { get; set; }
    }
}
namespace Repop_Companion.DataModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class Item_Weapons
    {
        public decimal itemID { get; set; }
        public Nullable<long> momentum { get; set; }
        public Nullable<long> endurance { get; set; }
        public Nullable<long> armorLightPenetration { get; set; }
        public Nullable<long> armorMediumPenetration { get; set; }
        public Nullable<long> armorHeavyPenetration { get; set; }
        public Nullable<long> minimalAmount { get; set; }
        public Nullable<long> minimalRange { get; set; }
        public Nullable<long> attackRange { get; set; }
        public Nullable<long> diminishedAmount { get; set; }
        public Nullable<long> diminishedRange { get; set; }
        public Nullable<long> maximumRange { get; set; }
        public string damageType { get; set; }
        public Nullable<long> damageAmount { get; set; }
        public Nullable<long> energyCost { get; set; }
        public Nullable<double> attackSpeed { get; set; }
        public string weaponCategory { get; set; }
        public string dualWield { get; set; }
    }
}
namespace Repop_Companion.DataModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class Path
    {
        public long pathID { get; set; }
        public string areaID { get; set; }
        public string name { get; set; }
        public string vect { get; set; }
        public string mis { get; set; }
    }
}
namespace Repop_Companion.DataModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class Prop
    {
        public long propID { get; set; }
        public Nullable<long> subsistenceID { get; set; }
        public Nullable<long> numHarvests { get; set; }
        public Nullable<long> toolID { get; set; }
        public Nullable<long> skillID { get; set; }
    }
}
namespace Repop_Companion.DataModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class Recipe
    {
        public long recipeID { get; set; }
        public string displayName { get; set; }
        public string displayDescription { get; set; }
        public long skillID { get; set; }
        public long steps { get; set; }
        public long ingredientWeight { get; set; }
        public long agentWeight { get; set; }
    }
}
namespace Repop_Companion.DataModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class Recipe_Agents
    {
        public long recipeID { get; set; }
        public long componentID { get; set; }
        public long count { get; set; }
        public long weight { get; set; }
    }
}
namespace Repop_Companion.DataModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class Recipe_Books
    {
        public long itemID { get; set; }
        public long recipeID { get; set; }
    }
}
namespace Repop_Companion.DataModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class Recipe_Ingredients
    {
        public long recipeID { get; set; }
        public long componentID { get; set; }
        public long count { get; set; }
        public long weight { get; set; }
        public long ingSlot { get; set; }
    }
}
namespace Repop_Companion.DataModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class Recipe_Results
    {
        public long recipeID { get; set; }
        public long groupID { get; set; }
        public long count { get; set; }
        public long grade { get; set; }
        public long level { get; set; }
        public long type { get; set; }
        public long resultID { get; set; }
        public long filter1ID { get; set; }
        public long filter2ID { get; set; }
        public long filter3ID { get; set; }
        public long filter4ID { get; set; }
        public long ingCount1 { get; set; }
        public long ingCount2 { get; set; }
        public long ingCount3 { get; set; }
        public long ingCount4 { get; set; }
    }
}
namespace Repop_Companion.DataModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class Recipe_Skill_Range
    {
        public long recipeID { get; set; }
        public long level { get; set; }
        public long minf { get; set; }
        public long mind { get; set; }
        public long minc { get; set; }
        public long minb { get; set; }
        public long mina { get; set; }
        public long minaa { get; set; }
        public long over1 { get; set; }
        public long over2 { get; set; }
    }
}
namespace Repop_Companion.DataModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class ResourceAttribute
    {
        public long resourceAttributeID { get; set; }
        public string displayName { get; set; }
        public string shortName { get; set; }
        public string socketPrimary { get; set; }
    }
}
namespace Repop_Companion.DataModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class Share
    {
        public long shareID { get; set; }
    }
}
namespace Repop_Companion.DataModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class Shop
    {
        public long shopID { get; set; }
        public string displayName { get; set; }
        public string displayDescription { get; set; }
        public Nullable<long> currencyType { get; set; }
    }
}
namespace Repop_Companion.DataModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class Shop_Inventory_List
    {
        public long inventoryID { get; set; }
        public Nullable<long> itemID { get; set; }
    }
}
namespace Repop_Companion.DataModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class Shop_To_Inventory_List
    {
        public long shopID { get; set; }
        public Nullable<long> inventoryID { get; set; }
    }
}
namespace Repop_Companion.DataModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class Skill
    {
        public long skillID { get; set; }
        public string displayName { get; set; }
        public string displayDescription { get; set; }
    }
}
namespace Repop_Companion.DataModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class Species
    {
        public long speciesID { get; set; }
        public string displayName { get; set; }
        public string displayDescription { get; set; }
        public string extractionType { get; set; }
    }
}
namespace Repop_Companion.DataModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class Species_Results
    {
        public long speciesID { get; set; }
        public long groupID { get; set; }
        public double chance { get; set; }
        public double chanceMultiplier { get; set; }
        public long itemID { get; set; }
        public long count { get; set; }
        public long type { get; set; }
        public long grade { get; set; }
        public long difficulty { get; set; }
    }
}
namespace Repop_Companion.DataModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class Structure
    {
        public long structureID { get; set; }
        public string displayName { get; set; }
        public Nullable<long> isHousingStructure { get; set; }
        public Nullable<long> isSiegingUnit { get; set; }
    }
}
namespace Repop_Companion.DataModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tip
    {
        public long tipID { get; set; }
        public string title { get; set; }
        public string displayDescription { get; set; }
    }
}
